# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api', models.CharField(max_length=500)),
                ('default_value', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('current_value', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('code', models.IntegerField(default=200)),
                ('https', models.IntegerField(default=0)),
                ('encrypt', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['id', 'api', 'code'],
            },
        ),
    ]
